apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- registry-agent-deployment.yaml

configMapGenerator:
    - name: registry-config
      files:
        - static-config/registry-agent-config.yml
    - name: registry-agent-config
      files:
        - dynamic-config/agentconfig.json