apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-agent-deployment
  labels:
    app: registry-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-agent
  template:
    metadata:
      labels:
        app: registry-agent
    spec:
      initContainers:
      - name: wait-for-registry
        image: busybox:1.31
        command: ['sh', '-c', "until wget --spider --tries 1 http://registry-service:5000/v2/; do printf 'waiting for registry...'; sleep 5; done"]
      containers:
      - name: registry-agent-container
        image: registry-service.tmpregistry.svc.cluster.local/registry-agent:latest
        volumeMounts:
          - name: registry-vol-config
            mountPath: /etc/docker/registry
            readOnly: true
          - name: registry-agent-config
            mountPath: /etc
            readOnly: true
          - name: registry-storage
            mountPath: /var/lib/registry
      volumes:
        - name: registry-vol-config
          configMap:
            name: registry-vol-config
            items:
              - key: registry-vol-config.yml
                path: config.yml
        - name: registry-agent-config
          configMap:
            name: registry-agent-config
            items:
              - key: agentconfig.json
                path: agentconfig.json
        - name: registry-storage
          emptyDir: {}