apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitea-deployment.yaml
- gitea-service.yaml
- gitea-storage.yaml
- gitea-ingress.yaml

configMapGenerator:
  - name: gitea-mirrors
    files:
      - dynamic-config/mirrors.csv
  - name: gitea-config
    files:
      - static-config/app.ini
  - name: gitea-init
    files:
      - static-config/init_gitea.sh