bases:
- base
- crds
- cluster-install

resources:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install
- https://github.com/argoproj-labs/argocd-notifications/manifests/bot

namespace: cddeployment1

images:
- name: argoproj/argocd
  newTag: v1.7.3
