apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/http01-ingress.yaml
- base/argo-cd-ui-ingress.yaml


patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-repo-server-deploy.yaml
- overlays/production/argocd-notifications-cm.yaml
- overlays/production/argocd-notifications-bot-service.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: cddeployment1

images:
- name: argoproj/argocd
  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
  newTag: 1.7.0-bc537c1e
- name: argoprojlabs/argocd-notifications
  newName: docker.pkg.github.com/argoproj-labs/argocd-notifications/argocd-notifications
  newTag: 0.7.0-582ae886
