version: 0.1
delete:
  enabled: true
log:
  accesslog: 
    disabled: false
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  cache:
    blobdescriptor: ""
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3